name: flutter_20240504
description: 신영우 최지연 모바일 청첩장 입니다.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # state management, dependency injection, route router_management
  get: ^4.6.6

  webview_universal: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: defaultFont
      fonts:
        - asset: assets/fonts/default_font_light.otf
          weight: 300
        - asset: assets/fonts/default_font_bold.otf
          weight: 500

    - family: nexonGothicFont
      fonts:
        - asset: assets/fonts/nexon_gothic_medium.otf
          weight: 400
        - asset: assets/fonts/nexon_gothic_bold.otf
          weight: 600
        - asset: assets/fonts/nexon_gothic_extra_bold.otf
          weight: 800
    - family: cormorantGaramondFont
      fonts:
        - asset: assets/fonts/CormorantGaramond-Regular.ttf

  assets:
    - assets/images/
    - assets/images/icons/