name: flutter_20240504
description: 신영우 최지연 모바일 청첩장 입니다.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # state management, dependency injection, route router_management
  get: ^4.6.6

  sakura_blizzard: ^3.1.5
  util_simple_3d: ^9.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: defaultFont
      fonts:
        - asset: assets/fonts/default_font_light.otf
          weight: 300
        - asset: assets/fonts/default_font_bold.otf
          weight: 500

  assets:
    - assets/images/
    - assets/images/icons/